import hashlib
import json
import os
import re
from datetime import datetime, timezone
import boto3
import requests
from bs4 import BeautifulSoup

# Where the post list comes from, and the two times that has gone wrong.
#
# 1. Blogger (retired 2026-06-26). BLOGGER_FEED_URL kept returning the same
#    frozen set forever once Blogger stopped receiving posts.
# 2. Scraping post-card anchors out of blog/index.html. That page is one page of
#    a paginated index, so this indexed the 24 newest posts and dropped the other
#    90 -- 79% of the site -- while logging success.
#
# Both failures look identical from outside: the run is green and the index is a
# subset. cards.json is generated by sync_blog.py from posts/ as one complete,
# newest-first list with real dates, so neither pagination nor card markup can
# shrink it again. The indexer still fetches each post's page for full text,
# because cards.json carries only a short excerpt.
CARDS_URL = os.environ.get("CARDS_URL", "https://jayanthkatta.com/blog/cards.json")
RESUME_URL = os.environ.get("RESUME_URL", "https://jayanthkatta.com/resume.html")
INDEX_BUCKET = os.environ["INDEX_BUCKET"]
REGION = os.environ["AWS_REGION_NAME"]
INDEX_KEY = "index/chunks.json"
SUMMARY_KEY = "index/summaries.json"
SUMMARY_MODEL = "us.anthropic.claude-haiku-4-5-20251001-v1:0"  # inference profile ID — Claude Haiku 4.5 requires cross-region inference, not direct on-demand invoke (verified live, 2026-07-24)
SUMMARY_MAX_CHARS = 6000  # enough context for a short post-level summary without unbounded token cost on long posts

CHUNK_SIZE = 400   # target words per chunk
CHUNK_OVERLAP = 50 # words of overlap between chunks

s3 = boto3.client("s3", region_name=REGION)
bedrock = boto3.client("bedrock-runtime", region_name=REGION)


def fetch_all_posts():
    """Every post on the site, from cards.json.

    This used to scrape the `post-card` anchors out of blog/index.html, with a
    comment calling that page "the single source of truth for all posts". It was,
    once. The blog is paginated now -- blog/index.html carries 24 cards and
    blog/page/2..5 carry the other 90 -- so the scrape had been indexing the 24
    most recent posts and silently dropping 79% of the site.

    It failed invisibly for exactly the reason a gate has to be explicit: the run
    still succeeded. Its own log said "found 24 post cards / Fetched 24 posts /
    Writing 163 chunks" and returned 200, every time. What a reader saw was the
    search answering "the provided content does not mention AWS Shield" while a
    3,000-word post about Shield sat on page 2, still serving, still in rss.xml,
    still in cards.json.

    cards.json is the right source rather than a five-page crawl: sync_blog.py
    generates it from posts/ as one authoritative list, it is already sorted
    newest-first, it carries the real publish date (which the scrape could not
    read, so every post was indexed with date=None), and it cannot be broken by a
    change to the card markup or by adding a sixth page of pagination.
    """
    resp = requests.get(CARDS_URL, timeout=30)
    resp.raise_for_status()
    cards = resp.json()

    entries = []
    for card in cards:
        slug = card.get("slug")
        if not slug:
            continue
        entries.append({
            "url": f"https://jayanthkatta.com/blog/{slug}/",
            "title": card.get("title", "") or slug,
            "date": card.get("date"),
        })
    # Sorted defensively rather than trusted: the recency document below is built
    # from the first five, so the order is load-bearing.
    entries.sort(key=lambda e: e.get("date") or "", reverse=True)

    print(f"cards.json: found {len(entries)} posts")

    posts, failed = [], []
    for rank, entry in enumerate(entries):
        url, title = entry["url"], entry["title"]
        try:
            page = requests.get(url, timeout=30)
            page.raise_for_status()
        except Exception as e:
            print(f"  FAILED {url}: {e}")
            failed.append(url)
            continue
        psoup = BeautifulSoup(page.text, "html.parser")
        content = psoup.find(id="jk-post") or psoup
        text = content.get_text(separator=" ")
        text = re.sub(r"\s+", " ", text).strip()
        if text:
            text = f"Title: {title}. {text}" if title else text
            posts.append({"title": title, "url": url, "text": text,
                          "date": entry.get("date"), "rank": rank})
        else:
            print(f"  FAILED {url}: page fetched but no text extracted")
            failed.append(url)

    # Say out loud when the index is incomplete. The whole 90-post gap survived
    # because a partial index and a complete one produced the same success.
    if failed:
        print(f"INCOMPLETE: {len(failed)} of {len(entries)} posts produced no "
              f"text and are ABSENT from the index: {', '.join(failed[:10])}"
              + (" ..." if len(failed) > 10 else ""))
    if len(posts) < len(entries) * 0.95:
        raise RuntimeError(
            f"only {len(posts)} of {len(entries)} posts could be indexed; "
            f"refusing to overwrite the index with a partial one"
        )

    return posts


def chunk_text(text, size=CHUNK_SIZE, overlap=CHUNK_OVERLAP):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + size, len(words))
        chunks.append(" ".join(words[start:end]))
        if end == len(words):
            break
        start += size - overlap
    return chunks


def embed(text):
    body = json.dumps({"inputText": text})
    resp = bedrock.invoke_model(
        modelId="amazon.titan-embed-text-v2:0",
        contentType="application/json",
        accept="application/json",
        body=body,
    )
    return json.loads(resp["body"].read())["embedding"]


def slug_from_url(url):
    # Post URLs are always https://jayanthkatta.com/blog/<slug>/ — matches
    # the slug sync_blog.py bakes into each page's summary-widget mount
    # point, so the two sides key on the same string with no translation.
    return url.rstrip("/").rsplit("/", 1)[-1]


def load_existing_summaries():
    try:
        obj = s3.get_object(Bucket=INDEX_BUCKET, Key=SUMMARY_KEY)
        return json.loads(obj["Body"].read())
    except s3.exceptions.NoSuchKey:
        return {}
    except Exception as e:
        print(f"Could not load existing summaries (starting fresh): {e}")
        return {}


# "At a glance" widget, replacing the old build-time keyword-extraction
# version (removed 2026-07-23 — it force-labeled sentences as Problem/Build/
# Catch regardless of fit, which broke on the 53-of-65 posts that aren't
# shaped like a weekly build post: troubleshooting posts, a day-N tutorial
# series, career posts). Generic Overview/Key detail/Takeaway labels are
# deliberately universal so ONE prompt/shape fits every post type — no
# per-post-type branching needed, and the model (not a keyword-frequency
# heuristic) decides what's actually worth saying about THIS post.
SUMMARY_PROMPT = """Below is the full text of a blog post. Write a 3-line "at a glance" \
summary for a reader deciding whether to read the full post. Be specific — name the actual \
technology, error, or technique involved, not a generic category. Respond with ONLY a JSON \
object, no other text, in exactly this shape:
{{"overview": "<one sentence: what this post is about>", \
"key_detail": "<one sentence: the single most important specific mechanism, decision, or fact>", \
"takeaway": "<one sentence: the most useful lesson or result for the reader>"}}

Title: {title}

POST TEXT:
{text}
"""


def generate_summary(title, text):
    prompt = SUMMARY_PROMPT.format(title=title, text=text[:SUMMARY_MAX_CHARS])
    try:
        resp = bedrock.invoke_model(
            modelId=SUMMARY_MODEL,
            contentType="application/json",
            accept="application/json",
            body=json.dumps({
                "anthropic_version": "bedrock-2023-05-31",
                "max_tokens": 300,
                "temperature": 0,
                "messages": [{"role": "user", "content": prompt}],
            }),
        )
        raw = json.loads(resp["body"].read())["content"][0]["text"].strip()
        # Model sometimes wraps JSON in a ```json fence despite instructions.
        raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw.strip())
        data = json.loads(raw)
        for key in ("overview", "key_detail", "takeaway"):
            if not data.get(key):
                raise ValueError(f"missing '{key}' in model output")
        return {"overview": data["overview"], "key_detail": data["key_detail"], "takeaway": data["takeaway"]}
    except Exception as e:
        print(f"  summary generation failed: {e}")
        return None


def build_summaries(posts):
    """Generate (or reuse cached) at-a-glance summaries, one Bedrock call per
    NEW or CHANGED post only — a content-hash cache means re-running the
    indexer on unchanged posts costs nothing extra."""
    existing = load_existing_summaries()
    updated = dict(existing)
    generated, reused, failed = 0, 0, 0

    for post in posts:
        slug = slug_from_url(post["url"])
        content_hash = hashlib.sha256(post["text"].encode("utf-8")).hexdigest()[:16]
        cached = existing.get(slug)
        if cached and cached.get("content_hash") == content_hash:
            reused += 1
            continue

        result = generate_summary(post["title"], post["text"])
        if result is None:
            failed += 1
            continue
        updated[slug] = {
            **result,
            "content_hash": content_hash,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "model": SUMMARY_MODEL,
        }
        generated += 1

    print(f"Summaries: {generated} generated, {reused} reused (unchanged), {failed} failed")
    return updated


def fetch_resume():
    resp = requests.get(RESUME_URL, timeout=30)
    resp.raise_for_status()
    text = BeautifulSoup(resp.text, "html.parser").get_text(separator=" ")
    text = re.sub(r"\s+", " ", text).strip()
    return [{"title": "Jayanth Katta — Resume", "url": "https://jayanthkatta.com/resume", "text": text, "date": None}]


def lambda_handler(event, context):
    # Said "RSS feed" for months after RSS stopped being the source, then
    # said nothing about which source replaced it. Name the real one.
    print("Fetching posts from cards.json...")
    posts = fetch_all_posts()
    print(f"Fetched {len(posts)} posts")

    print("Fetching resume...")
    resume_docs = fetch_resume()
    print("Resume fetched")

    print("Building at-a-glance summaries...")
    summaries = build_summaries(posts)  # resume has no post page to attach a summary widget to — posts only
    s3.put_object(
        Bucket=INDEX_BUCKET,
        Key=SUMMARY_KEY,
        Body=json.dumps(summaries),
        ContentType="application/json",
    )
    print(f"Wrote {len(summaries)} summaries to s3://{INDEX_BUCKET}/{SUMMARY_KEY}")

    # Synthetic metadata document describing post order — picked up by semantic
    # search for any recency phrasing ("today's post", "new post", "what did you
    # publish", etc.) without relying on a brittle keyword list in the query Lambda.
    top5 = posts[:5]
    recency_lines = "\n".join(
        f"{i+1}. {p['title']} — {p['url']}" for i, p in enumerate(top5)
    )
    recency_text = (
        f"Blog post publication order (most recent first). "
        f"The latest post, today's post, and the newest post is: {top5[0]['title']} at {top5[0]['url']}. "
        f"Recent posts in order:\n{recency_lines}"
    )
    recency_doc = {
        "title": "Blog post index — most recent first",
        "url": top5[0]["url"],
        "text": recency_text,
        "date": None,
        "rank": -1,  # sentinel: this is a metadata doc, not a real post
    }

    records = []
    for post in [recency_doc] + posts + resume_docs:
        for chunk in chunk_text(post["text"]):
            vector = embed(chunk)
            records.append(
                {
                    "post_title": post["title"],
                    "post_url": post["url"],
                    "post_date": post["date"],
                    "post_rank": post.get("rank"),
                    "chunk_text": chunk,
                    "embedding": vector,
                }
            )

    print(f"Writing {len(records)} chunks to s3://{INDEX_BUCKET}/{INDEX_KEY}")
    s3.put_object(
        Bucket=INDEX_BUCKET,
        Key=INDEX_KEY,
        Body=json.dumps(records),
        ContentType="application/json",
    )
    return {"statusCode": 200, "body": f"Indexed {len(records)} chunks from {len(posts)} posts, {len(summaries)} summaries cached"}
